name: Create and publish OpencCR Docker image to Docker hub

on:
  push:
    branches:
      - "main"
  release:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: itechuw/opencr

jobs:
  build-and-push-opencr-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/opencr
          push: true
          load: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{github.repository}}:latest
          cache-to: type=inline